# Generated by Django 3.2.9 on 2021-11-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Rating', models.FloatField()),
                ('Date', models.DateField()),
                ('Location', models.CharField(max_length=20)),
                ('Feedback', models.TextField(max_length=100)),
            ],
        ),
    ]
